package com.model;

/**
 * TJibing generated by MyEclipse Persistence Tools
 */

public class TJibing implements java.io.Serializable
{

	private Integer id;
	private String mingcheng;
	private String zhengzhuang;
	private int renyuanId;

	private String huanshijian;
	private String yisheng;
	
	private TRenyuan renyuan;
	
	
	
	public String getHuanshijian()
	{
		return huanshijian;
	}
	public void setHuanshijian(String huanshijian)
	{
		this.huanshijian = huanshijian;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	
	public TRenyuan getRenyuan()
	{
		return renyuan;
	}
	public void setRenyuan(TRenyuan renyuan)
	{
		this.renyuan = renyuan;
	}
	
	public int getRenyuanId()
	{
		return renyuanId;
	}
	public void setRenyuanId(int renyuanId)
	{
		this.renyuanId = renyuanId;
	}
	public String getYisheng()
	{
		return yisheng;
	}
	public void setYisheng(String yisheng)
	{
		this.yisheng = yisheng;
	}
	public String getZhengzhuang()
	{
		return zhengzhuang;
	}
	public void setZhengzhuang(String zhengzhuang)
	{
		this.zhengzhuang = zhengzhuang;
	}
    
}