package com.model;

/**
 * TTijian generated by MyEclipse Persistence Tools
 */

public class TTijian implements java.io.Serializable
{

	private Integer id;
	private Integer renyuanId;
	private String shijian;
	private String yisheng;

	private String xueya;
	private String tizhong;
	private String kouchun;
	private String chilie;
	
	private String shili;
	private String tingli;
	
	private TRenyuan renyuan;
	
	public String getChilie()
	{
		return chilie;
	}
	public void setChilie(String chilie)
	{
		this.chilie = chilie;
	}
	public Integer getId()
	{
		return id;
	}
	
	public TRenyuan getRenyuan()
	{
		return renyuan;
	}
	public void setRenyuan(TRenyuan renyuan)
	{
		this.renyuan = renyuan;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getKouchun()
	{
		return kouchun;
	}
	public void setKouchun(String kouchun)
	{
		this.kouchun = kouchun;
	}
	public Integer getRenyuanId()
	{
		return renyuanId;
	}
	public void setRenyuanId(Integer renyuanId)
	{
		this.renyuanId = renyuanId;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public String getShili()
	{
		return shili;
	}
	public void setShili(String shili)
	{
		this.shili = shili;
	}
	public String getTingli()
	{
		return tingli;
	}
	public void setTingli(String tingli)
	{
		this.tingli = tingli;
	}
	public String getTizhong()
	{
		return tizhong;
	}
	public void setTizhong(String tizhong)
	{
		this.tizhong = tizhong;
	}
	public String getXueya()
	{
		return xueya;
	}
	public void setXueya(String xueya)
	{
		this.xueya = xueya;
	}
	public String getYisheng()
	{
		return yisheng;
	}
	public void setYisheng(String yisheng)
	{
		this.yisheng = yisheng;
	}

}