package com.model;

/**
 * TYinyue generated by MyEclipse Persistence Tools
 */

public class TYinyue implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer catelogId;

	private String name;

	private String fujian;

	private String fujianYuanshiming;

	private String geshou;

	private String shijian;

	private Integer userId=0;//µã»÷ÂÊ

	private String del;

	// Constructors

	/** default constructor */
	public TYinyue()
	{
	}

	/** full constructor */
	public TYinyue(Integer catelogId, String name, String fujian,
			String fujianYuanshiming, String geshou, String shijian,
			Integer userId, String del)
	{
		this.catelogId = catelogId;
		this.name = name;
		this.fujian = fujian;
		this.fujianYuanshiming = fujianYuanshiming;
		this.geshou = geshou;
		this.shijian = shijian;
		this.userId = userId;
		this.del = del;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getCatelogId()
	{
		return this.catelogId;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getFujian()
	{
		return this.fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public String getFujianYuanshiming()
	{
		return this.fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public String getGeshou()
	{
		return this.geshou;
	}

	public void setGeshou(String geshou)
	{
		this.geshou = geshou;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}