package com.model;

/**
 * TRenyuan generated by MyEclipse Persistence Tools
 */

public class TRenyuan implements java.io.Serializable
{


	private Integer id;
	private String xingming;
	private String xingbie;
	private String nianling;

	private String dizhi;
	private String chusheng;
	private String shenfenzheng;
	private String lianxi;

	private String danwei;
	private String menzu;
	private String wenhua;
	private String hunyin;
	
	private String beizhu;
	
	
	public String getBeizhu()
	{
		return beizhu;
	}
	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}
	public String getChusheng()
	{
		return chusheng;
	}
	public void setChusheng(String chusheng)
	{
		this.chusheng = chusheng;
	}
	public String getDanwei()
	{
		return danwei;
	}
	public void setDanwei(String danwei)
	{
		this.danwei = danwei;
	}
	public String getDizhi()
	{
		return dizhi;
	}
	public void setDizhi(String dizhi)
	{
		this.dizhi = dizhi;
	}
	public String getHunyin()
	{
		return hunyin;
	}
	public void setHunyin(String hunyin)
	{
		this.hunyin = hunyin;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getLianxi()
	{
		return lianxi;
	}
	public void setLianxi(String lianxi)
	{
		this.lianxi = lianxi;
	}
	public String getMenzu()
	{
		return menzu;
	}
	public void setMenzu(String menzu)
	{
		this.menzu = menzu;
	}
	public String getNianling()
	{
		return nianling;
	}
	public void setNianling(String nianling)
	{
		this.nianling = nianling;
	}
	public String getShenfenzheng()
	{
		return shenfenzheng;
	}
	public void setShenfenzheng(String shenfenzheng)
	{
		this.shenfenzheng = shenfenzheng;
	}
	public String getWenhua()
	{
		return wenhua;
	}
	public void setWenhua(String wenhua)
	{
		this.wenhua = wenhua;
	}
	public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}
	public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

}